apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgresql-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
        app: voting-app
    spec:
      containers:
      - name: postgresql
        image: postgres
        ports:
          - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-sv
spec:
  selector:
    name: postgresql
    app: voting-app
  ports:
    - port: 5432
      targetPort: 5432