apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom-example
  name: prom-example
spec:
  type: LoadBalancer
  ports:
  - name: prom-example-service
    port: 5000
    targetPort: 1234
  selector:
    app: prom-example