apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
        app: voting-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-sv
spec:
  selector:
    name: redis
    app: voting-app
  ports:
    - port: 6379
      targetPort: 6379