apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: voting-app-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      name: voting-app
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app-vote
        image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
      - name: voting-app-result
        image: dockersamples/examplevotingapp_result
        ports:
          - containerPort: 81
      - name: voting-app-worker
        image: dockersamples/examplevotingapp_worker
        ports:
          - containerPort: 82

---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-sv
spec:
  selector:
    name: voting-app
    app: voting-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 81
      targetPort: 81
    - port: 82
      targetPort: 82